<?php
/**
 * Created by PhpStorm.
 * User: Tu TV
 * Date: 15/12/2015
 * Time: 7:11 PM
 *
 * Google Fonts
 *
 * @package Restaurant_WP
 */

/**
 * Get google fonts
 *
 * @return array
 */

function restaurant_wp_google_fonts() {
	$fonts = array(
		array( 'name' => 'ABeeZee', 'category' => 'sans-serif' ),
		array( 'name' => 'Abel', 'category' => 'sans-serif' ),
		array( 'name' => 'Abril Fatface', 'category' => 'display' ),
		array( 'name' => 'Aclonica', 'category' => 'sans-serif' ),
		array( 'name' => 'Acme', 'category' => 'sans-serif' ),
		array( 'name' => 'Actor', 'category' => 'sans-serif' ),
		array( 'name' => 'Adamina', 'category' => 'serif' ),
		array( 'name' => 'Advent Pro', 'category' => 'sans-serif' ),
		array( 'name' => 'Aguafina Script', 'category' => 'handwriting' ),
		array( 'name' => 'Akronim', 'category' => 'display' ),
		array( 'name' => 'Aladin', 'category' => 'handwriting' ),
		array( 'name' => 'Aldrich', 'category' => 'sans-serif' ),
		array( 'name' => 'Alef', 'category' => 'sans-serif' ),
		array( 'name' => 'Alegreya', 'category' => 'serif' ),
		array( 'name' => 'Alegreya SC', 'category' => 'serif' ),
		array( 'name' => 'Alegreya Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Alegreya Sans SC', 'category' => 'sans-serif' ),
		array( 'name' => 'Alex Brush', 'category' => 'handwriting' ),
		array( 'name' => 'Alfa Slab One', 'category' => 'display' ),
		array( 'name' => 'Alice', 'category' => 'serif' ),
		array( 'name' => 'Alike', 'category' => 'serif' ),
		array( 'name' => 'Alike Angular', 'category' => 'serif' ),
		array( 'name' => 'Allan', 'category' => 'display' ),
		array( 'name' => 'Allerta', 'category' => 'sans-serif' ),
		array( 'name' => 'Allerta Stencil', 'category' => 'sans-serif' ),
		array( 'name' => 'Allura', 'category' => 'handwriting' ),
		array( 'name' => 'Almendra', 'category' => 'serif' ),
		array( 'name' => 'Almendra Display', 'category' => 'display' ),
		array( 'name' => 'Almendra SC', 'category' => 'serif' ),
		array( 'name' => 'Amarante', 'category' => 'display' ),
		array( 'name' => 'Amaranth', 'category' => 'sans-serif' ),
		array( 'name' => 'Amatic SC', 'category' => 'handwriting' ),
		array( 'name' => 'Amethysta', 'category' => 'serif' ),
		array( 'name' => 'Amiri', 'category' => 'serif' ),
		array( 'name' => 'Amita', 'category' => 'handwriting' ),
		array( 'name' => 'Anaheim', 'category' => 'sans-serif' ),
		array( 'name' => 'Andada', 'category' => 'serif' ),
		array( 'name' => 'Andika', 'category' => 'sans-serif' ),
		array( 'name' => 'Angkor', 'category' => 'display' ),
		array( 'name' => 'Annie Use Your Telescope', 'category' => 'handwriting' ),
		array( 'name' => 'Anonymous Pro', 'category' => 'monospace' ),
		array( 'name' => 'Antic', 'category' => 'sans-serif' ),
		array( 'name' => 'Antic Didone', 'category' => 'serif' ),
		array( 'name' => 'Antic Slab', 'category' => 'serif' ),
		array( 'name' => 'Anton', 'category' => 'sans-serif' ),
		array( 'name' => 'Arapey', 'category' => 'serif' ),
		array( 'name' => 'Arbutus', 'category' => 'display' ),
		array( 'name' => 'Arbutus Slab', 'category' => 'serif' ),
		array( 'name' => 'Architects Daughter', 'category' => 'handwriting' ),
		array( 'name' => 'Archivo Black', 'category' => 'sans-serif' ),
		array( 'name' => 'Archivo Narrow', 'category' => 'sans-serif' ),
		array( 'name' => 'Arimo', 'category' => 'sans-serif' ),
		array( 'name' => 'Arizonia', 'category' => 'handwriting' ),
		array( 'name' => 'Armata', 'category' => 'sans-serif' ),
		array( 'name' => 'Artifika', 'category' => 'serif' ),
		array( 'name' => 'Arvo', 'category' => 'serif' ),
		array( 'name' => 'Arya', 'category' => 'sans-serif' ),
		array( 'name' => 'Asap', 'category' => 'sans-serif' ),
		array( 'name' => 'Asar', 'category' => 'serif' ),
		array( 'name' => 'Asset', 'category' => 'display' ),
		array( 'name' => 'Astloch', 'category' => 'display' ),
		array( 'name' => 'Asul', 'category' => 'sans-serif' ),
		array( 'name' => 'Atomic Age', 'category' => 'display' ),
		array( 'name' => 'Aubrey', 'category' => 'display' ),
		array( 'name' => 'Audiowide', 'category' => 'display' ),
		array( 'name' => 'Autour One', 'category' => 'display' ),
		array( 'name' => 'Average', 'category' => 'serif' ),
		array( 'name' => 'Average Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Averia Gruesa Libre', 'category' => 'display' ),
		array( 'name' => 'Averia Libre', 'category' => 'display' ),
		array( 'name' => 'Averia Sans Libre', 'category' => 'display' ),
		array( 'name' => 'Averia Serif Libre', 'category' => 'display' ),
		array( 'name' => 'Bad Script', 'category' => 'handwriting' ),
		array( 'name' => 'Balthazar', 'category' => 'serif' ),
		array( 'name' => 'Bangers', 'category' => 'display' ),
		array( 'name' => 'Basic', 'category' => 'sans-serif' ),
		array( 'name' => 'Battambang', 'category' => 'display' ),
		array( 'name' => 'Baumans', 'category' => 'display' ),
		array( 'name' => 'Bayon', 'category' => 'display' ),
		array( 'name' => 'Belgrano', 'category' => 'serif' ),
		array( 'name' => 'Belleza', 'category' => 'sans-serif' ),
		array( 'name' => 'BenchNine', 'category' => 'sans-serif' ),
		array( 'name' => 'Bentham', 'category' => 'serif' ),
		array( 'name' => 'Berkshire Swash', 'category' => 'handwriting' ),
		array( 'name' => 'Bevan', 'category' => 'display' ),
		array( 'name' => 'Bigelow Rules', 'category' => 'display' ),
		array( 'name' => 'Bigshot One', 'category' => 'display' ),
		array( 'name' => 'Bilbo', 'category' => 'handwriting' ),
		array( 'name' => 'Bilbo Swash Caps', 'category' => 'handwriting' ),
		array( 'name' => 'Biryani', 'category' => 'sans-serif' ),
		array( 'name' => 'Bitter', 'category' => 'serif' ),
		array( 'name' => 'Black Ops One', 'category' => 'display' ),
		array( 'name' => 'Bokor', 'category' => 'display' ),
		array( 'name' => 'Bonbon', 'category' => 'handwriting' ),
		array( 'name' => 'Boogaloo', 'category' => 'display' ),
		array( 'name' => 'Bowlby One', 'category' => 'display' ),
		array( 'name' => 'Bowlby One SC', 'category' => 'display' ),
		array( 'name' => 'Brawler', 'category' => 'serif' ),
		array( 'name' => 'Bree Serif', 'category' => 'serif' ),
		array( 'name' => 'Bubblegum Sans', 'category' => 'display' ),
		array( 'name' => 'Bubbler One', 'category' => 'sans-serif' ),
		array( 'name' => 'Buda', 'category' => 'display' ),
		array( 'name' => 'Buenard', 'category' => 'serif' ),
		array( 'name' => 'Butcherman', 'category' => 'display' ),
		array( 'name' => 'Butterfly Kids', 'category' => 'handwriting' ),
		array( 'name' => 'Cabin', 'category' => 'sans-serif' ),
		array( 'name' => 'Cabin Condensed', 'category' => 'sans-serif' ),
		array( 'name' => 'Cabin Sketch', 'category' => 'display' ),
		array( 'name' => 'Caesar Dressing', 'category' => 'display' ),
		array( 'name' => 'Cagliostro', 'category' => 'sans-serif' ),
		array( 'name' => 'Calligraffitti', 'category' => 'handwriting' ),
		array( 'name' => 'Cambay', 'category' => 'sans-serif' ),
		array( 'name' => 'Cambo', 'category' => 'serif' ),
		array( 'name' => 'Candal', 'category' => 'sans-serif' ),
		array( 'name' => 'Cantarell', 'category' => 'sans-serif' ),
		array( 'name' => 'Cantata One', 'category' => 'serif' ),
		array( 'name' => 'Cantora One', 'category' => 'sans-serif' ),
		array( 'name' => 'Capriola', 'category' => 'sans-serif' ),
		array( 'name' => 'Cardo', 'category' => 'serif' ),
		array( 'name' => 'Carme', 'category' => 'sans-serif' ),
		array( 'name' => 'Carrois Gothic', 'category' => 'sans-serif' ),
		array( 'name' => 'Carrois Gothic SC', 'category' => 'sans-serif' ),
		array( 'name' => 'Carter One', 'category' => 'display' ),
		array( 'name' => 'Catamaran', 'category' => 'sans-serif' ),
		array( 'name' => 'Caudex', 'category' => 'serif' ),
		array( 'name' => 'Caveat', 'category' => 'handwriting' ),
		array( 'name' => 'Caveat Brush', 'category' => 'handwriting' ),
		array( 'name' => 'Cedarville Cursive', 'category' => 'handwriting' ),
		array( 'name' => 'Ceviche One', 'category' => 'display' ),
		array( 'name' => 'Changa One', 'category' => 'display' ),
		array( 'name' => 'Chango', 'category' => 'display' ),
		array( 'name' => 'Chau Philomene One', 'category' => 'sans-serif' ),
		array( 'name' => 'Chela One', 'category' => 'display' ),
		array( 'name' => 'Chelsea Market', 'category' => 'display' ),
		array( 'name' => 'Chenla', 'category' => 'display' ),
		array( 'name' => 'Cherry Cream Soda', 'category' => 'display' ),
		array( 'name' => 'Cherry Swash', 'category' => 'display' ),
		array( 'name' => 'Chewy', 'category' => 'display' ),
		array( 'name' => 'Chicle', 'category' => 'display' ),
		array( 'name' => 'Chivo', 'category' => 'sans-serif' ),
		array( 'name' => 'Chonburi', 'category' => 'display' ),
		array( 'name' => 'Cinzel', 'category' => 'serif' ),
		array( 'name' => 'Cinzel Decorative', 'category' => 'display' ),
		array( 'name' => 'Clicker Script', 'category' => 'handwriting' ),
		array( 'name' => 'Coda', 'category' => 'display' ),
		array( 'name' => 'Coda Caption', 'category' => 'sans-serif' ),
		array( 'name' => 'Codystar', 'category' => 'display' ),
		array( 'name' => 'Combo', 'category' => 'display' ),
		array( 'name' => 'Comfortaa', 'category' => 'display' ),
		array( 'name' => 'Coming Soon', 'category' => 'handwriting' ),
		array( 'name' => 'Concert One', 'category' => 'display' ),
		array( 'name' => 'Condiment', 'category' => 'handwriting' ),
		array( 'name' => 'Content', 'category' => 'display' ),
		array( 'name' => 'Contrail One', 'category' => 'display' ),
		array( 'name' => 'Convergence', 'category' => 'sans-serif' ),
		array( 'name' => 'Cookie', 'category' => 'handwriting' ),
		array( 'name' => 'Copse', 'category' => 'serif' ),
		array( 'name' => 'Corben', 'category' => 'display' ),
		array( 'name' => 'Courgette', 'category' => 'handwriting' ),
		array( 'name' => 'Cousine', 'category' => 'monospace' ),
		array( 'name' => 'Coustard', 'category' => 'serif' ),
		array( 'name' => 'Covered By Your Grace', 'category' => 'handwriting' ),
		array( 'name' => 'Crafty Girls', 'category' => 'handwriting' ),
		array( 'name' => 'Creepster', 'category' => 'display' ),
		array( 'name' => 'Crete Round', 'category' => 'serif' ),
		array( 'name' => 'Crimson Text', 'category' => 'serif' ),
		array( 'name' => 'Croissant One', 'category' => 'display' ),
		array( 'name' => 'Crushed', 'category' => 'display' ),
		array( 'name' => 'Cuprum', 'category' => 'sans-serif' ),
		array( 'name' => 'Cutive', 'category' => 'serif' ),
		array( 'name' => 'Cutive Mono', 'category' => 'monospace' ),
		array( 'name' => 'Damion', 'category' => 'handwriting' ),
		array( 'name' => 'Dancing Script', 'category' => 'handwriting' ),
		array( 'name' => 'Dangrek', 'category' => 'display' ),
		array( 'name' => 'Dawning of a New Day', 'category' => 'handwriting' ),
		array( 'name' => 'Days One', 'category' => 'sans-serif' ),
		array( 'name' => 'Dekko', 'category' => 'handwriting' ),
		array( 'name' => 'Delius', 'category' => 'handwriting' ),
		array( 'name' => 'Delius Swash Caps', 'category' => 'handwriting' ),
		array( 'name' => 'Delius Unicase', 'category' => 'handwriting' ),
		array( 'name' => 'Della Respira', 'category' => 'serif' ),
		array( 'name' => 'Denk One', 'category' => 'sans-serif' ),
		array( 'name' => 'Devonshire', 'category' => 'handwriting' ),
		array( 'name' => 'Dhurjati', 'category' => 'sans-serif' ),
		array( 'name' => 'Didact Gothic', 'category' => 'sans-serif' ),
		array( 'name' => 'Diplomata', 'category' => 'display' ),
		array( 'name' => 'Diplomata SC', 'category' => 'display' ),
		array( 'name' => 'Domine', 'category' => 'serif' ),
		array( 'name' => 'Donegal One', 'category' => 'serif' ),
		array( 'name' => 'Doppio One', 'category' => 'sans-serif' ),
		array( 'name' => 'Dorsa', 'category' => 'sans-serif' ),
		array( 'name' => 'Dosis', 'category' => 'sans-serif' ),
		array( 'name' => 'Dr Sugiyama', 'category' => 'handwriting' ),
		array( 'name' => 'Droid Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Droid Sans Mono', 'category' => 'monospace' ),
		array( 'name' => 'Droid Serif', 'category' => 'serif' ),
		array( 'name' => 'Duru Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Dynalight', 'category' => 'display' ),
		array( 'name' => 'EB Garamond', 'category' => 'serif' ),
		array( 'name' => 'Eagle Lake', 'category' => 'handwriting' ),
		array( 'name' => 'Eater', 'category' => 'display' ),
		array( 'name' => 'Economica', 'category' => 'sans-serif' ),
		array( 'name' => 'Eczar', 'category' => 'serif' ),
		array( 'name' => 'Ek Mukta', 'category' => 'sans-serif' ),
		array( 'name' => 'Electrolize', 'category' => 'sans-serif' ),
		array( 'name' => 'Elsie', 'category' => 'display' ),
		array( 'name' => 'Elsie Swash Caps', 'category' => 'display' ),
		array( 'name' => 'Emblema One', 'category' => 'display' ),
		array( 'name' => 'Emilys Candy', 'category' => 'display' ),
		array( 'name' => 'Engagement', 'category' => 'handwriting' ),
		array( 'name' => 'Englebert', 'category' => 'sans-serif' ),
		array( 'name' => 'Enriqueta', 'category' => 'serif' ),
		array( 'name' => 'Erica One', 'category' => 'display' ),
		array( 'name' => 'Esteban', 'category' => 'serif' ),
		array( 'name' => 'Euphoria Script', 'category' => 'handwriting' ),
		array( 'name' => 'Ewert', 'category' => 'display' ),
		array( 'name' => 'Exo', 'category' => 'sans-serif' ),
		array( 'name' => 'Exo 2', 'category' => 'sans-serif' ),
		array( 'name' => 'Expletus Sans', 'category' => 'display' ),
		array( 'name' => 'Fanwood Text', 'category' => 'serif' ),
		array( 'name' => 'Fascinate', 'category' => 'display' ),
		array( 'name' => 'Fascinate Inline', 'category' => 'display' ),
		array( 'name' => 'Faster One', 'category' => 'display' ),
		array( 'name' => 'Fasthand', 'category' => 'serif' ),
		array( 'name' => 'Fauna One', 'category' => 'serif' ),
		array( 'name' => 'Federant', 'category' => 'display' ),
		array( 'name' => 'Federo', 'category' => 'sans-serif' ),
		array( 'name' => 'Felipa', 'category' => 'handwriting' ),
		array( 'name' => 'Fenix', 'category' => 'serif' ),
		array( 'name' => 'Finger Paint', 'category' => 'display' ),
		array( 'name' => 'Fira Mono', 'category' => 'monospace' ),
		array( 'name' => 'Fira Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Fjalla One', 'category' => 'sans-serif' ),
		array( 'name' => 'Fjord One', 'category' => 'serif' ),
		array( 'name' => 'Flamenco', 'category' => 'display' ),
		array( 'name' => 'Flavors', 'category' => 'display' ),
		array( 'name' => 'Fondamento', 'category' => 'handwriting' ),
		array( 'name' => 'Fontdiner Swanky', 'category' => 'display' ),
		array( 'name' => 'Forum', 'category' => 'display' ),
		array( 'name' => 'Francois One', 'category' => 'sans-serif' ),
		array( 'name' => 'Freckle Face', 'category' => 'display' ),
		array( 'name' => 'Fredericka the Great', 'category' => 'display' ),
		array( 'name' => 'Fredoka One', 'category' => 'display' ),
		array( 'name' => 'Freehand', 'category' => 'display' ),
		array( 'name' => 'Fresca', 'category' => 'sans-serif' ),
		array( 'name' => 'Frijole', 'category' => 'display' ),
		array( 'name' => 'Fruktur', 'category' => 'display' ),
		array( 'name' => 'Fugaz One', 'category' => 'display' ),
		array( 'name' => 'GFS Didot', 'category' => 'serif' ),
		array( 'name' => 'GFS Neohellenic', 'category' => 'sans-serif' ),
		array( 'name' => 'Gabriela', 'category' => 'serif' ),
		array( 'name' => 'Gafata', 'category' => 'sans-serif' ),
		array( 'name' => 'Galdeano', 'category' => 'sans-serif' ),
		array( 'name' => 'Galindo', 'category' => 'display' ),
		array( 'name' => 'Gentium Basic', 'category' => 'serif' ),
		array( 'name' => 'Gentium Book Basic', 'category' => 'serif' ),
		array( 'name' => 'Geo', 'category' => 'sans-serif' ),
		array( 'name' => 'Geostar', 'category' => 'display' ),
		array( 'name' => 'Geostar Fill', 'category' => 'display' ),
		array( 'name' => 'Germania One', 'category' => 'display' ),
		array( 'name' => 'Gidugu', 'category' => 'sans-serif' ),
		array( 'name' => 'Gilda Display', 'category' => 'serif' ),
		array( 'name' => 'Give You Glory', 'category' => 'handwriting' ),
		array( 'name' => 'Glass Antiqua', 'category' => 'display' ),
		array( 'name' => 'Glegoo', 'category' => 'serif' ),
		array( 'name' => 'Gloria Hallelujah', 'category' => 'handwriting' ),
		array( 'name' => 'Goblin One', 'category' => 'display' ),
		array( 'name' => 'Gochi Hand', 'category' => 'handwriting' ),
		array( 'name' => 'Gorditas', 'category' => 'display' ),
		array( 'name' => 'Goudy Bookletter 1911', 'category' => 'serif' ),
		array( 'name' => 'Graduate', 'category' => 'display' ),
		array( 'name' => 'Grand Hotel', 'category' => 'handwriting' ),
		array( 'name' => 'Gravitas One', 'category' => 'display' ),
		array( 'name' => 'Great Vibes', 'category' => 'handwriting' ),
		array( 'name' => 'Griffy', 'category' => 'display' ),
		array( 'name' => 'Gruppo', 'category' => 'display' ),
		array( 'name' => 'Gudea', 'category' => 'sans-serif' ),
		array( 'name' => 'Gurajada', 'category' => 'serif' ),
		array( 'name' => 'Habibi', 'category' => 'serif' ),
		array( 'name' => 'Halant', 'category' => 'serif' ),
		array( 'name' => 'Hammersmith One', 'category' => 'sans-serif' ),
		array( 'name' => 'Hanalei', 'category' => 'display' ),
		array( 'name' => 'Hanalei Fill', 'category' => 'display' ),
		array( 'name' => 'Handlee', 'category' => 'handwriting' ),
		array( 'name' => 'Hanuman', 'category' => 'serif' ),
		array( 'name' => 'Happy Monkey', 'category' => 'display' ),
		array( 'name' => 'Headland One', 'category' => 'serif' ),
		array( 'name' => 'Henny Penny', 'category' => 'display' ),
		array( 'name' => 'Herr Von Muellerhoff', 'category' => 'handwriting' ),
		array( 'name' => 'Hind', 'category' => 'sans-serif' ),
		array( 'name' => 'Hind Siliguri', 'category' => 'sans-serif' ),
		array( 'name' => 'Hind Vadodara', 'category' => 'sans-serif' ),
		array( 'name' => 'Holtwood One SC', 'category' => 'serif' ),
		array( 'name' => 'Homemade Apple', 'category' => 'handwriting' ),
		array( 'name' => 'Homenaje', 'category' => 'sans-serif' ),
		array( 'name' => 'IM Fell DW Pica', 'category' => 'serif' ),
		array( 'name' => 'IM Fell DW Pica SC', 'category' => 'serif' ),
		array( 'name' => 'IM Fell Double Pica', 'category' => 'serif' ),
		array( 'name' => 'IM Fell Double Pica SC', 'category' => 'serif' ),
		array( 'name' => 'IM Fell English', 'category' => 'serif' ),
		array( 'name' => 'IM Fell English SC', 'category' => 'serif' ),
		array( 'name' => 'IM Fell French Canon', 'category' => 'serif' ),
		array( 'name' => 'IM Fell French Canon SC', 'category' => 'serif' ),
		array( 'name' => 'IM Fell Great Primer', 'category' => 'serif' ),
		array( 'name' => 'IM Fell Great Primer SC', 'category' => 'serif' ),
		array( 'name' => 'Iceberg', 'category' => 'display' ),
		array( 'name' => 'Iceland', 'category' => 'display' ),
		array( 'name' => 'Imprima', 'category' => 'sans-serif' ),
		array( 'name' => 'Inconsolata', 'category' => 'monospace' ),
		array( 'name' => 'Inder', 'category' => 'sans-serif' ),
		array( 'name' => 'Indie Flower', 'category' => 'handwriting' ),
		array( 'name' => 'Inika', 'category' => 'serif' ),
		array( 'name' => 'Inknut Antiqua', 'category' => 'serif' ),
		array( 'name' => 'Irish Grover', 'category' => 'display' ),
		array( 'name' => 'Istok Web', 'category' => 'sans-serif' ),
		array( 'name' => 'Italiana', 'category' => 'serif' ),
		array( 'name' => 'Italianno', 'category' => 'handwriting' ),
		array( 'name' => 'Itim', 'category' => 'handwriting' ),
		array( 'name' => 'Jacques Francois', 'category' => 'serif' ),
		array( 'name' => 'Jacques Francois Shadow', 'category' => 'display' ),
		array( 'name' => 'Jaldi', 'category' => 'sans-serif' ),
		array( 'name' => 'Jim Nightshade', 'category' => 'handwriting' ),
		array( 'name' => 'Jockey One', 'category' => 'sans-serif' ),
		array( 'name' => 'Jolly Lodger', 'category' => 'display' ),
		array( 'name' => 'Josefin Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Josefin Slab', 'category' => 'serif' ),
		array( 'name' => 'Joti One', 'category' => 'display' ),
		array( 'name' => 'Judson', 'category' => 'serif' ),
		array( 'name' => 'Julee', 'category' => 'handwriting' ),
		array( 'name' => 'Julius Sans One', 'category' => 'sans-serif' ),
		array( 'name' => 'Junge', 'category' => 'serif' ),
		array( 'name' => 'Jura', 'category' => 'sans-serif' ),
		array( 'name' => 'Just Another Hand', 'category' => 'handwriting' ),
		array( 'name' => 'Just Me Again Down Here', 'category' => 'handwriting' ),
		array( 'name' => 'Kadwa', 'category' => 'serif' ),
		array( 'name' => 'Kalam', 'category' => 'handwriting' ),
		array( 'name' => 'Kameron', 'category' => 'serif' ),
		array( 'name' => 'Kanit', 'category' => 'sans-serif' ),
		array( 'name' => 'Kantumruy', 'category' => 'sans-serif' ),
		array( 'name' => 'Karla', 'category' => 'sans-serif' ),
		array( 'name' => 'Karma', 'category' => 'serif' ),
		array( 'name' => 'Kaushan Script', 'category' => 'handwriting' ),
		array( 'name' => 'Kavoon', 'category' => 'display' ),
		array( 'name' => 'Kdam Thmor', 'category' => 'display' ),
		array( 'name' => 'Keania One', 'category' => 'display' ),
		array( 'name' => 'Kelly Slab', 'category' => 'display' ),
		array( 'name' => 'Kenia', 'category' => 'display' ),
		array( 'name' => 'Khand', 'category' => 'sans-serif' ),
		array( 'name' => 'Khmer', 'category' => 'display' ),
		array( 'name' => 'Khula', 'category' => 'sans-serif' ),
		array( 'name' => 'Kite One', 'category' => 'sans-serif' ),
		array( 'name' => 'Knewave', 'category' => 'display' ),
		array( 'name' => 'Kotta One', 'category' => 'serif' ),
		array( 'name' => 'Koulen', 'category' => 'display' ),
		array( 'name' => 'Kranky', 'category' => 'display' ),
		array( 'name' => 'Kreon', 'category' => 'serif' ),
		array( 'name' => 'Kristi', 'category' => 'handwriting' ),
		array( 'name' => 'Krona One', 'category' => 'sans-serif' ),
		array( 'name' => 'Kurale', 'category' => 'serif' ),
		array( 'name' => 'La Belle Aurore', 'category' => 'handwriting' ),
		array( 'name' => 'Laila', 'category' => 'serif' ),
		array( 'name' => 'Lakki Reddy', 'category' => 'handwriting' ),
		array( 'name' => 'Lancelot', 'category' => 'display' ),
		array( 'name' => 'Lateef', 'category' => 'handwriting' ),
		array( 'name' => 'Lato', 'category' => 'sans-serif' ),
		array( 'name' => 'League Script', 'category' => 'handwriting' ),
		array( 'name' => 'Leckerli One', 'category' => 'handwriting' ),
		array( 'name' => 'Ledger', 'category' => 'serif' ),
		array( 'name' => 'Lekton', 'category' => 'sans-serif' ),
		array( 'name' => 'Lemon', 'category' => 'display' ),
		array( 'name' => 'Libre Baskerville', 'category' => 'serif' ),
		array( 'name' => 'Life Savers', 'category' => 'display' ),
		array( 'name' => 'Lilita One', 'category' => 'display' ),
		array( 'name' => 'Lily Script One', 'category' => 'display' ),
		array( 'name' => 'Limelight', 'category' => 'display' ),
		array( 'name' => 'Linden Hill', 'category' => 'serif' ),
		array( 'name' => 'Lobster', 'category' => 'display' ),
		array( 'name' => 'Lobster Two', 'category' => 'display' ),
		array( 'name' => 'Londrina Outline', 'category' => 'display' ),
		array( 'name' => 'Londrina Shadow', 'category' => 'display' ),
		array( 'name' => 'Londrina Sketch', 'category' => 'display' ),
		array( 'name' => 'Londrina Solid', 'category' => 'display' ),
		array( 'name' => 'Lora', 'category' => 'serif' ),
		array( 'name' => 'Love Ya Like A Sister', 'category' => 'display' ),
		array( 'name' => 'Loved by the King', 'category' => 'handwriting' ),
		array( 'name' => 'Lovers Quarrel', 'category' => 'handwriting' ),
		array( 'name' => 'Luckiest Guy', 'category' => 'display' ),
		array( 'name' => 'Lusitana', 'category' => 'serif' ),
		array( 'name' => 'Lustria', 'category' => 'serif' ),
		array( 'name' => 'Macondo', 'category' => 'display' ),
		array( 'name' => 'Macondo Swash Caps', 'category' => 'display' ),
		array( 'name' => 'Magra', 'category' => 'sans-serif' ),
		array( 'name' => 'Maiden Orange', 'category' => 'display' ),
		array( 'name' => 'Mako', 'category' => 'sans-serif' ),
		array( 'name' => 'Mallanna', 'category' => 'sans-serif' ),
		array( 'name' => 'Mandali', 'category' => 'sans-serif' ),
		array( 'name' => 'Marcellus', 'category' => 'serif' ),
		array( 'name' => 'Marcellus SC', 'category' => 'serif' ),
		array( 'name' => 'Marck Script', 'category' => 'handwriting' ),
		array( 'name' => 'Margarine', 'category' => 'display' ),
		array( 'name' => 'Marko One', 'category' => 'serif' ),
		array( 'name' => 'Marmelad', 'category' => 'sans-serif' ),
		array( 'name' => 'Martel', 'category' => 'serif' ),
		array( 'name' => 'Martel Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Marvel', 'category' => 'sans-serif' ),
		array( 'name' => 'Mate', 'category' => 'serif' ),
		array( 'name' => 'Mate SC', 'category' => 'serif' ),
		array( 'name' => 'Maven Pro', 'category' => 'sans-serif' ),
		array( 'name' => 'McLaren', 'category' => 'display' ),
		array( 'name' => 'Meddon', 'category' => 'handwriting' ),
		array( 'name' => 'MedievalSharp', 'category' => 'display' ),
		array( 'name' => 'Medula One', 'category' => 'display' ),
		array( 'name' => 'Megrim', 'category' => 'display' ),
		array( 'name' => 'Meie Script', 'category' => 'handwriting' ),
		array( 'name' => 'Merienda', 'category' => 'handwriting' ),
		array( 'name' => 'Merienda One', 'category' => 'handwriting' ),
		array( 'name' => 'Merriweather', 'category' => 'serif' ),
		array( 'name' => 'Merriweather Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Metal', 'category' => 'display' ),
		array( 'name' => 'Metal Mania', 'category' => 'display' ),
		array( 'name' => 'Metamorphous', 'category' => 'display' ),
		array( 'name' => 'Metrophobic', 'category' => 'sans-serif' ),
		array( 'name' => 'Michroma', 'category' => 'sans-serif' ),
		array( 'name' => 'Milonga', 'category' => 'display' ),
		array( 'name' => 'Miltonian', 'category' => 'display' ),
		array( 'name' => 'Miltonian Tattoo', 'category' => 'display' ),
		array( 'name' => 'Miniver', 'category' => 'display' ),
		array( 'name' => 'Miss Fajardose', 'category' => 'handwriting' ),
		array( 'name' => 'Modak', 'category' => 'display' ),
		array( 'name' => 'Modern Antiqua', 'category' => 'display' ),
		array( 'name' => 'Molengo', 'category' => 'sans-serif' ),
		array( 'name' => 'Molle', 'category' => 'handwriting' ),
		array( 'name' => 'Monda', 'category' => 'sans-serif' ),
		array( 'name' => 'Monofett', 'category' => 'display' ),
		array( 'name' => 'Monoton', 'category' => 'display' ),
		array( 'name' => 'Monsieur La Doulaise', 'category' => 'handwriting' ),
		array( 'name' => 'Montaga', 'category' => 'serif' ),
		array( 'name' => 'Montez', 'category' => 'handwriting' ),
		array( 'name' => 'Montserrat', 'category' => 'sans-serif' ),
		array( 'name' => 'Montserrat Alternates', 'category' => 'sans-serif' ),
		array( 'name' => 'Montserrat Subrayada', 'category' => 'sans-serif' ),
		array( 'name' => 'Moul', 'category' => 'display' ),
		array( 'name' => 'Moulpali', 'category' => 'display' ),
		array( 'name' => 'Mountains of Christmas', 'category' => 'display' ),
		array( 'name' => 'Mouse Memoirs', 'category' => 'sans-serif' ),
		array( 'name' => 'Mr Bedfort', 'category' => 'handwriting' ),
		array( 'name' => 'Mr Dafoe', 'category' => 'handwriting' ),
		array( 'name' => 'Mr De Haviland', 'category' => 'handwriting' ),
		array( 'name' => 'Mrs Saint Delafield', 'category' => 'handwriting' ),
		array( 'name' => 'Mrs Sheppards', 'category' => 'handwriting' ),
		array( 'name' => 'Muli', 'category' => 'sans-serif' ),
		array( 'name' => 'Mystery Quest', 'category' => 'display' ),
		array( 'name' => 'NTR', 'category' => 'sans-serif' ),
		array( 'name' => 'Neucha', 'category' => 'handwriting' ),
		array( 'name' => 'Neuton', 'category' => 'serif' ),
		array( 'name' => 'New Rocker', 'category' => 'display' ),
		array( 'name' => 'News Cycle', 'category' => 'sans-serif' ),
		array( 'name' => 'Niconne', 'category' => 'handwriting' ),
		array( 'name' => 'Nixie One', 'category' => 'display' ),
		array( 'name' => 'Nobile', 'category' => 'sans-serif' ),
		array( 'name' => 'Nokora', 'category' => 'serif' ),
		array( 'name' => 'Norican', 'category' => 'handwriting' ),
		array( 'name' => 'Nosifer', 'category' => 'display' ),
		array( 'name' => 'Nothing You Could Do', 'category' => 'handwriting' ),
		array( 'name' => 'Noticia Text', 'category' => 'serif' ),
		array( 'name' => 'Noto Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Noto Serif', 'category' => 'serif' ),
		array( 'name' => 'Nova Cut', 'category' => 'display' ),
		array( 'name' => 'Nova Flat', 'category' => 'display' ),
		array( 'name' => 'Nova Mono', 'category' => 'monospace' ),
		array( 'name' => 'Nova Oval', 'category' => 'display' ),
		array( 'name' => 'Nova Round', 'category' => 'display' ),
		array( 'name' => 'Nova Script', 'category' => 'display' ),
		array( 'name' => 'Nova Slim', 'category' => 'display' ),
		array( 'name' => 'Nova Square', 'category' => 'display' ),
		array( 'name' => 'Numans', 'category' => 'sans-serif' ),
		array( 'name' => 'Nunito', 'category' => 'sans-serif' ),
		array( 'name' => 'Odor Mean Chey', 'category' => 'display' ),
		array( 'name' => 'Offside', 'category' => 'display' ),
		array( 'name' => 'Old Standard TT', 'category' => 'serif' ),
		array( 'name' => 'Oldenburg', 'category' => 'display' ),
		array( 'name' => 'Oleo Script', 'category' => 'display' ),
		array( 'name' => 'Oleo Script Swash Caps', 'category' => 'display' ),
		array( 'name' => 'Open Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Open Sans Condensed', 'category' => 'sans-serif' ),
		array( 'name' => 'Oranienbaum', 'category' => 'serif' ),
		array( 'name' => 'Orbitron', 'category' => 'sans-serif' ),
		array( 'name' => 'Oregano', 'category' => 'display' ),
		array( 'name' => 'Orienta', 'category' => 'sans-serif' ),
		array( 'name' => 'Original Surfer', 'category' => 'display' ),
		array( 'name' => 'Oswald', 'category' => 'sans-serif' ),
		array( 'name' => 'Over the Rainbow', 'category' => 'handwriting' ),
		array( 'name' => 'Overlock', 'category' => 'display' ),
		array( 'name' => 'Overlock SC', 'category' => 'display' ),
		array( 'name' => 'Ovo', 'category' => 'serif' ),
		array( 'name' => 'Oxygen', 'category' => 'sans-serif' ),
		array( 'name' => 'Oxygen Mono', 'category' => 'monospace' ),
		array( 'name' => 'PT Mono', 'category' => 'monospace' ),
		array( 'name' => 'PT Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'PT Sans Caption', 'category' => 'sans-serif' ),
		array( 'name' => 'PT Sans Narrow', 'category' => 'sans-serif' ),
		array( 'name' => 'PT Serif', 'category' => 'serif' ),
		array( 'name' => 'PT Serif Caption', 'category' => 'serif' ),
		array( 'name' => 'Pacifico', 'category' => 'handwriting' ),
		array( 'name' => 'Palanquin', 'category' => 'sans-serif' ),
		array( 'name' => 'Palanquin Dark', 'category' => 'sans-serif' ),
		array( 'name' => 'Paprika', 'category' => 'display' ),
		array( 'name' => 'Parisienne', 'category' => 'handwriting' ),
		array( 'name' => 'Passero One', 'category' => 'display' ),
		array( 'name' => 'Passion One', 'category' => 'display' ),
		array( 'name' => 'Pathway Gothic One', 'category' => 'sans-serif' ),
		array( 'name' => 'Patrick Hand', 'category' => 'handwriting' ),
		array( 'name' => 'Patrick Hand SC', 'category' => 'handwriting' ),
		array( 'name' => 'Patua One', 'category' => 'display' ),
		array( 'name' => 'Paytone One', 'category' => 'sans-serif' ),
		array( 'name' => 'Peddana', 'category' => 'serif' ),
		array( 'name' => 'Peralta', 'category' => 'display' ),
		array( 'name' => 'Permanent Marker', 'category' => 'handwriting' ),
		array( 'name' => 'Petit Formal Script', 'category' => 'handwriting' ),
		array( 'name' => 'Petrona', 'category' => 'serif' ),
		array( 'name' => 'Philosopher', 'category' => 'sans-serif' ),
		array( 'name' => 'Piedra', 'category' => 'display' ),
		array( 'name' => 'Pinyon Script', 'category' => 'handwriting' ),
		array( 'name' => 'Pirata One', 'category' => 'display' ),
		array( 'name' => 'Plaster', 'category' => 'display' ),
		array( 'name' => 'Play', 'category' => 'sans-serif' ),
		array( 'name' => 'Playball', 'category' => 'display' ),
		array( 'name' => 'Playfair Display', 'category' => 'serif' ),
		array( 'name' => 'Playfair Display SC', 'category' => 'serif' ),
		array( 'name' => 'Podkova', 'category' => 'serif' ),
		array( 'name' => 'Poiret One', 'category' => 'display' ),
		array( 'name' => 'Poller One', 'category' => 'display' ),
		array( 'name' => 'Poly', 'category' => 'serif' ),
		array( 'name' => 'Pompiere', 'category' => 'display' ),
		array( 'name' => 'Pontano Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Poppins', 'category' => 'sans-serif' ),
		array( 'name' => 'Port Lligat Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Port Lligat Slab', 'category' => 'serif' ),
		array( 'name' => 'Pragati Narrow', 'category' => 'sans-serif' ),
		array( 'name' => 'Prata', 'category' => 'serif' ),
		array( 'name' => 'Preahvihear', 'category' => 'display' ),
		array( 'name' => 'Press Start 2P', 'category' => 'display' ),
		array( 'name' => 'Princess Sofia', 'category' => 'handwriting' ),
		array( 'name' => 'Prociono', 'category' => 'serif' ),
		array( 'name' => 'Prosto One', 'category' => 'display' ),
		array( 'name' => 'Puritan', 'category' => 'sans-serif' ),
		array( 'name' => 'Purple Purse', 'category' => 'display' ),
		array( 'name' => 'Quando', 'category' => 'serif' ),
		array( 'name' => 'Quantico', 'category' => 'sans-serif' ),
		array( 'name' => 'Quattrocento', 'category' => 'serif' ),
		array( 'name' => 'Quattrocento Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Questrial', 'category' => 'sans-serif' ),
		array( 'name' => 'Quicksand', 'category' => 'sans-serif' ),
		array( 'name' => 'Quintessential', 'category' => 'handwriting' ),
		array( 'name' => 'Qwigley', 'category' => 'handwriting' ),
		array( 'name' => 'Racing Sans One', 'category' => 'display' ),
		array( 'name' => 'Radley', 'category' => 'serif' ),
		array( 'name' => 'Rajdhani', 'category' => 'sans-serif' ),
		array( 'name' => 'Raleway', 'category' => 'sans-serif' ),
		array( 'name' => 'Raleway Dots', 'category' => 'display' ),
		array( 'name' => 'Ramabhadra', 'category' => 'sans-serif' ),
		array( 'name' => 'Ramaraja', 'category' => 'serif' ),
		array( 'name' => 'Rambla', 'category' => 'sans-serif' ),
		array( 'name' => 'Rammetto One', 'category' => 'display' ),
		array( 'name' => 'Ranchers', 'category' => 'display' ),
		array( 'name' => 'Rancho', 'category' => 'handwriting' ),
		array( 'name' => 'Ranga', 'category' => 'display' ),
		array( 'name' => 'Rationale', 'category' => 'sans-serif' ),
		array( 'name' => 'Ravi Prakash', 'category' => 'display' ),
		array( 'name' => 'Redressed', 'category' => 'handwriting' ),
		array( 'name' => 'Reenie Beanie', 'category' => 'handwriting' ),
		array( 'name' => 'Revalia', 'category' => 'display' ),
		array( 'name' => 'Rhodium Libre', 'category' => 'serif' ),
		array( 'name' => 'Ribeye', 'category' => 'display' ),
		array( 'name' => 'Ribeye Marrow', 'category' => 'display' ),
		array( 'name' => 'Righteous', 'category' => 'display' ),
		array( 'name' => 'Risque', 'category' => 'display' ),
		array( 'name' => 'Roboto', 'category' => 'sans-serif' ),
		array( 'name' => 'Roboto Condensed', 'category' => 'sans-serif' ),
		array( 'name' => 'Roboto Mono', 'category' => 'monospace' ),
		array( 'name' => 'Roboto Slab', 'category' => 'serif' ),
		array( 'name' => 'Rochester', 'category' => 'handwriting' ),
		array( 'name' => 'Rock Salt', 'category' => 'handwriting' ),
		array( 'name' => 'Rokkitt', 'category' => 'serif' ),
		array( 'name' => 'Romanesco', 'category' => 'handwriting' ),
		array( 'name' => 'Ropa Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Rosario', 'category' => 'sans-serif' ),
		array( 'name' => 'Rosarivo', 'category' => 'serif' ),
		array( 'name' => 'Rouge Script', 'category' => 'handwriting' ),
		array( 'name' => 'Rozha One', 'category' => 'serif' ),
		array( 'name' => 'Rubik', 'category' => 'sans-serif' ),
		array( 'name' => 'Rubik Mono One', 'category' => 'sans-serif' ),
		array( 'name' => 'Rubik One', 'category' => 'sans-serif' ),
		array( 'name' => 'Ruda', 'category' => 'sans-serif' ),
		array( 'name' => 'Rufina', 'category' => 'serif' ),
		array( 'name' => 'Ruge Boogie', 'category' => 'handwriting' ),
		array( 'name' => 'Ruluko', 'category' => 'sans-serif' ),
		array( 'name' => 'Rum Raisin', 'category' => 'sans-serif' ),
		array( 'name' => 'Ruslan Display', 'category' => 'display' ),
		array( 'name' => 'Russo One', 'category' => 'sans-serif' ),
		array( 'name' => 'Ruthie', 'category' => 'handwriting' ),
		array( 'name' => 'Rye', 'category' => 'display' ),
		array( 'name' => 'Sacramento', 'category' => 'handwriting' ),
		array( 'name' => 'Sahitya', 'category' => 'serif' ),
		array( 'name' => 'Sail', 'category' => 'display' ),
		array( 'name' => 'Salsa', 'category' => 'display' ),
		array( 'name' => 'Sanchez', 'category' => 'serif' ),
		array( 'name' => 'Sancreek', 'category' => 'display' ),
		array( 'name' => 'Sansita One', 'category' => 'display' ),
		array( 'name' => 'Sarala', 'category' => 'sans-serif' ),
		array( 'name' => 'Sarina', 'category' => 'display' ),
		array( 'name' => 'Sarpanch', 'category' => 'sans-serif' ),
		array( 'name' => 'Satisfy', 'category' => 'handwriting' ),
		array( 'name' => 'Scada', 'category' => 'sans-serif' ),
		array( 'name' => 'Scheherazade', 'category' => 'serif' ),
		array( 'name' => 'Schoolbell', 'category' => 'handwriting' ),
		array( 'name' => 'Seaweed Script', 'category' => 'display' ),
		array( 'name' => 'Sevillana', 'category' => 'display' ),
		array( 'name' => 'Seymour One', 'category' => 'sans-serif' ),
		array( 'name' => 'Shadows Into Light', 'category' => 'handwriting' ),
		array( 'name' => 'Shadows Into Light Two', 'category' => 'handwriting' ),
		array( 'name' => 'Shanti', 'category' => 'sans-serif' ),
		array( 'name' => 'Share', 'category' => 'display' ),
		array( 'name' => 'Share Tech', 'category' => 'sans-serif' ),
		array( 'name' => 'Share Tech Mono', 'category' => 'monospace' ),
		array( 'name' => 'Shojumaru', 'category' => 'display' ),
		array( 'name' => 'Short Stack', 'category' => 'handwriting' ),
		array( 'name' => 'Siemreap', 'category' => 'display' ),
		array( 'name' => 'Sigmar One', 'category' => 'display' ),
		array( 'name' => 'Signika', 'category' => 'sans-serif' ),
		array( 'name' => 'Signika Negative', 'category' => 'sans-serif' ),
		array( 'name' => 'Simonetta', 'category' => 'display' ),
		array( 'name' => 'Sintony', 'category' => 'sans-serif' ),
		array( 'name' => 'Sirin Stencil', 'category' => 'display' ),
		array( 'name' => 'Six Caps', 'category' => 'sans-serif' ),
		array( 'name' => 'Skranji', 'category' => 'display' ),
		array( 'name' => 'Slabo 13px', 'category' => 'serif' ),
		array( 'name' => 'Slabo 27px', 'category' => 'serif' ),
		array( 'name' => 'Slackey', 'category' => 'display' ),
		array( 'name' => 'Smokum', 'category' => 'display' ),
		array( 'name' => 'Smythe', 'category' => 'display' ),
		array( 'name' => 'Sniglet', 'category' => 'display' ),
		array( 'name' => 'Snippet', 'category' => 'sans-serif' ),
		array( 'name' => 'Snowburst One', 'category' => 'display' ),
		array( 'name' => 'Sofadi One', 'category' => 'display' ),
		array( 'name' => 'Sofia', 'category' => 'handwriting' ),
		array( 'name' => 'Sonsie One', 'category' => 'display' ),
		array( 'name' => 'Sorts Mill Goudy', 'category' => 'serif' ),
		array( 'name' => 'Source Code Pro', 'category' => 'monospace' ),
		array( 'name' => 'Source Sans Pro', 'category' => 'sans-serif' ),
		array( 'name' => 'Source Serif Pro', 'category' => 'serif' ),
		array( 'name' => 'Special Elite', 'category' => 'display' ),
		array( 'name' => 'Spicy Rice', 'category' => 'display' ),
		array( 'name' => 'Spinnaker', 'category' => 'sans-serif' ),
		array( 'name' => 'Spirax', 'category' => 'display' ),
		array( 'name' => 'Squada One', 'category' => 'display' ),
		array( 'name' => 'Sree Krushnadevaraya', 'category' => 'serif' ),
		array( 'name' => 'Stalemate', 'category' => 'handwriting' ),
		array( 'name' => 'Stalinist One', 'category' => 'display' ),
		array( 'name' => 'Stardos Stencil', 'category' => 'display' ),
		array( 'name' => 'Stint Ultra Condensed', 'category' => 'display' ),
		array( 'name' => 'Stint Ultra Expanded', 'category' => 'display' ),
		array( 'name' => 'Stoke', 'category' => 'serif' ),
		array( 'name' => 'Strait', 'category' => 'sans-serif' ),
		array( 'name' => 'Sue Ellen Francisco', 'category' => 'handwriting' ),
		array( 'name' => 'Sumana', 'category' => 'serif' ),
		array( 'name' => 'Sunshiney', 'category' => 'handwriting' ),
		array( 'name' => 'Supermercado One', 'category' => 'display' ),
		array( 'name' => 'Sura', 'category' => 'serif' ),
		array( 'name' => 'Suranna', 'category' => 'serif' ),
		array( 'name' => 'Suravaram', 'category' => 'serif' ),
		array( 'name' => 'Suwannaphum', 'category' => 'display' ),
		array( 'name' => 'Swanky and Moo Moo', 'category' => 'handwriting' ),
		array( 'name' => 'Syncopate', 'category' => 'sans-serif' ),
		array( 'name' => 'Tangerine', 'category' => 'handwriting' ),
		array( 'name' => 'Taprom', 'category' => 'display' ),
		array( 'name' => 'Tauri', 'category' => 'sans-serif' ),
		array( 'name' => 'Teko', 'category' => 'sans-serif' ),
		array( 'name' => 'Telex', 'category' => 'sans-serif' ),
		array( 'name' => 'Tenali Ramakrishna', 'category' => 'sans-serif' ),
		array( 'name' => 'Tenor Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Text Me One', 'category' => 'sans-serif' ),
		array( 'name' => 'The Girl Next Door', 'category' => 'handwriting' ),
		array( 'name' => 'Tienne', 'category' => 'serif' ),
		array( 'name' => 'Tillana', 'category' => 'handwriting' ),
		array( 'name' => 'Timmana', 'category' => 'sans-serif' ),
		array( 'name' => 'Tinos', 'category' => 'serif' ),
		array( 'name' => 'Titan One', 'category' => 'display' ),
		array( 'name' => 'Titillium Web', 'category' => 'sans-serif' ),
		array( 'name' => 'Trade Winds', 'category' => 'display' ),
		array( 'name' => 'Trocchi', 'category' => 'serif' ),
		array( 'name' => 'Trochut', 'category' => 'display' ),
		array( 'name' => 'Trykker', 'category' => 'serif' ),
		array( 'name' => 'Tulpen One', 'category' => 'display' ),
		array( 'name' => 'Ubuntu', 'category' => 'sans-serif' ),
		array( 'name' => 'Ubuntu Condensed', 'category' => 'sans-serif' ),
		array( 'name' => 'Ubuntu Mono', 'category' => 'monospace' ),
		array( 'name' => 'Ultra', 'category' => 'serif' ),
		array( 'name' => 'Uncial Antiqua', 'category' => 'display' ),
		array( 'name' => 'Underdog', 'category' => 'display' ),
		array( 'name' => 'Unica One', 'category' => 'display' ),
		array( 'name' => 'UnifrakturCook', 'category' => 'display' ),
		array( 'name' => 'UnifrakturMaguntia', 'category' => 'display' ),
		array( 'name' => 'Unkempt', 'category' => 'display' ),
		array( 'name' => 'Unlock', 'category' => 'display' ),
		array( 'name' => 'Unna', 'category' => 'serif' ),
		array( 'name' => 'VT323', 'category' => 'monospace' ),
		array( 'name' => 'Vampiro One', 'category' => 'display' ),
		array( 'name' => 'Varela', 'category' => 'sans-serif' ),
		array( 'name' => 'Varela Round', 'category' => 'sans-serif' ),
		array( 'name' => 'Vast Shadow', 'category' => 'display' ),
		array( 'name' => 'Vesper Libre', 'category' => 'serif' ),
		array( 'name' => 'Vibur', 'category' => 'handwriting' ),
		array( 'name' => 'Vidaloka', 'category' => 'serif' ),
		array( 'name' => 'Viga', 'category' => 'sans-serif' ),
		array( 'name' => 'Voces', 'category' => 'display' ),
		array( 'name' => 'Volkhov', 'category' => 'serif' ),
		array( 'name' => 'Vollkorn', 'category' => 'serif' ),
		array( 'name' => 'Voltaire', 'category' => 'sans-serif' ),
		array( 'name' => 'Waiting for the Sunrise', 'category' => 'handwriting' ),
		array( 'name' => 'Wallpoet', 'category' => 'display' ),
		array( 'name' => 'Walter Turncoat', 'category' => 'handwriting' ),
		array( 'name' => 'Warnes', 'category' => 'display' ),
		array( 'name' => 'Wellfleet', 'category' => 'display' ),
		array( 'name' => 'Wendy One', 'category' => 'sans-serif' ),
		array( 'name' => 'Wire One', 'category' => 'sans-serif' ),
		array( 'name' => 'Work Sans', 'category' => 'sans-serif' ),
		array( 'name' => 'Yanone Kaffeesatz', 'category' => 'sans-serif' ),
		array( 'name' => 'Yantramanav', 'category' => 'sans-serif' ),
		array( 'name' => 'Yellowtail', 'category' => 'handwriting' ),
		array( 'name' => 'Yeseva One', 'category' => 'display' ),
		array( 'name' => 'Yesteryear', 'category' => 'handwriting' ),
		array( 'name' => 'Zeyada', 'category' => 'handwriting' ),
	);

	return $fonts;
}

/**
 * Get array google fonts
 *
 * @return array
 */
function restaurant_wp_get_list_google_fonts() {
	$google_fonts = restaurant_wp_google_fonts();

	$fonts = array();
	foreach ( $google_fonts as $index => $font ) {
		$fonts[$font['name']] = $font['name'] . ' (' . $font['category'] . ')';
	}

	return $fonts;
}